# Generated by Django 2.2.3 on 2019-08-21 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('reciever', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=30)),
                ('inbox', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to='app.Inbox')),
                ('outbox', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='app.Outbox')),
            ],
        ),
        migrations.AddField(
            model_name='outbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outboxuser', to='app.UserAccount'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxusers', to='app.UserAccount'),
        ),
    ]
