# Generated by Django 2.2.4 on 2019-08-22 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190821_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='user_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_inbox', to='app.UserAccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbox',
            name='user_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_outbox', to='app.UserAccount'),
            preserve_default=False,
        ),
    ]
